[build]
  command = "npm run start"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  DB_HOST = "your_database_host"
  DB_USER = "your_database_username"
  DB_PASSWORD = "your_database_password"
  DB_NAME = "your_database_name"